[simulation]
  name    = "1d_polar_cap"
  engine  = "srpic"
  runtime = 60.0

[grid]
  resolution = 2048
  extent     = [[0.0, 100.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields    = [["ATMOSPHERE", "ABSORB"]]
    particles = [["ATMOSPHERE", "ABSORB"]]

    [grid.boundaries.absorb]
      ds = 1.0

    [grid.boundaries.atmosphere]
      temperature = 0.1
      density     = 10.0
      height      = 0.02
      species     = [1, 2]
      ds          = 2.0

[scales]
  larmor0    = 2e-5
  skindepth0 = 0.01

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

  [algorithms.gca]
    e_ovr_b_max = 0.9
    larmor_max  = 1.0

[particles]
  ppc0           = 5.0
  use_weights    = true
  clear_interval = 100

  [[particles.species]]
    label    = "e-"
    mass     = 1.0
    charge   = -1.0
    maxnpart = 1e7
    pusher   = "Boris,GCA"

  [[particles.species]]
    label    = "e+"
    mass     = 1.0
    charge   = 1.0
    maxnpart = 1e7
    pusher   = "Boris,GCA"

[setup]
  Bsurf  = 1.0
  period = 1.0

[output]
  format = "hdf5"

  [output.fields]
    interval_time = 1.0
    quantities    = ["N_1", "N_2", "E", "B", "T00"]

  [output.particles]
    enable = false

  [output.spectra]
    enable = true

[diagnostics]
  interval       = 50
  colored_stdout = true
