[simulation]
  name = "turbulence"
  engine = "srpic"
  runtime = 1000.0

[grid]
  resolution = [5500, 5500]
  extent = [[-512.0, 512.0], [-512.0, 512.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]

    
[scales]
  larmor0 = 0.05
  skindepth0 = 0.2

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 32.0
  sort_interval = 0

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 5e8

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 5e8

[setup]
mode1 = 32
mode2 = 64
b_rms = 1.0
bz = 1.0
temperature = 0.3
 
 
[output]
  format = "hdf5"
  interval_time = 1.0
  
  [output.fields]
     quantities = ["N", "E", "B", "J", "T00", "T0i", "Tij"]

  [output.particles]
     enable = false
